/* eslint-disable no-undef */
let ctx = '/caizhi_manage'
let mockCtx = 'https://openapi-test.tengmoney.com/mock/33'
let wexinLogin = ''
// 财智2.0
if (SERVER === 'wwwserver') {
  // 生产服
  wexinLogin =
    'https://open.work.weixin.qq.com/wwopen/sso/3rd_qrConnect?appid=ww535912ccc9fb5be5&redirect_uri=https%3A%2F%2Fwww.tenwit.com%2Fcaizhi_manage%2Findex%2Fhome.do&state=caizhi_admin&usertype=member'
  // 'https://open.work.weixin.qq.com/wwopen/sso/3rd_qrConnect?appid=ww535912ccc9fb5be5&redirect_uri=https%3A%2F%2Fwww.tengmoney.com%2Fcaizhi_manage%2Findex%2Fhome.do&state=caizhi_admin&usertype=member'
} else if (SERVER === 'testserver') {
  // 测试服(新翰登录)
  wexinLogin =
    'https://open.work.weixin.qq.com/wwopen/sso/3rd_qrConnect?appid=ww8c83d949a80b562d&redirect_uri=https%3A%2F%2Ftest.tengmoney.com%2Fcaizhi_manage%2Findex%2Fhome.do&state=caizhi_admin&usertype=member'
} else if (SERVER === 'uatserver') {
  // uat
  ctx = '/caizhi_manage'
  wexinLogin =
    'https://open.work.weixin.qq.com/wwopen/sso/3rd_qrConnect?appid=ww8c83d949a80b562d&redirect_uri=https%3A%2F%2Fuat.tengmoney.com%2Fcaizhi_manage%2Findex%2Fhome.do&state=caizhi_admin&usertype=member'
} else {
  // 开发服(新皓登录)或者本地开发
  // SERVER是'devserver'或者'localhost'
  ctx = SERVER === 'localhost' ? '/develop/caizhi_manage' : '/caizhi_manage'
  // ctx = SERVER === 'localhost' ? '/test/caizhi_manage' : '/caizhi_manage'
  // ctx = SERVER === 'localhost' ? '/www/caizhi_manage' : '/caizhi_manage'
  // ctx = SERVER === 'localhost' ? '/uat/caizhi_manage' : '/caizhi_manage'
  wexinLogin =
    'https://open.work.weixin.qq.com/wwopen/sso/3rd_qrConnect?appid=wwc8b0e2b9d33c6340&redirect_uri=https%3A%2F%2Fdev.tengmoney.com%2Fcaizhi_manage%2Findex%2Fhome.do&state=caizhi_admin&usertype=member'
}

export default {
  // 微信登录 测试服和生产服url不一样
  wexinLogin: wexinLogin,
  // 本地开发调试用getOauth接口 微信测试环境会走wexinLogin自动登录  jin.su
  performanceReportList: `${ctx}/api/bank/query`,
  performanceReportDownload: `${ctx}/api/bank/export`,
  organizationUpload: `${ctx}/api/organization/upload`,
  progressResult: `${ctx}/api/organization/progressResult`,
  finishProgress: `${ctx}/api/organization/finishProgress`,
  organizationErrorList: `${ctx}/api/organization/errorList`,
  organizationExport: `${ctx}/api/organization/export`,
  newsParse: `${ctx}/api/activity/parse.do`,
  greetSave: `${ctx}/api/activity/save.do`,
  greetEdit: `${ctx}/api/activity/edit.do`,
  greetDelete: `${ctx}/api/activity/delete.do`,
  greetList: `${ctx}/api/activity/page/list.do`,
  choicestCreate: `${ctx}/api/choicest/create`,
  choicestUpdate: `${ctx}/api/choicest/update`,
  choicestDelete: `${ctx}/api/choicest/delete`,
  choicestList: `${ctx}/api/choicest/list`,
  choicestDetail: `${ctx}/api/choicest/detail`,
  taskList: `${ctx}/api/task/manage/data/getAll`,
  stateTaskList: `${ctx}/api/task/manage/data/export_status`,
  exportTaskList: `${ctx}/api/task/manage/data/export`,
  getOauth: `${ctx}/index/auth.do?userId=cjie&corpId=wwc8b0e2b9d33c6340`,
  userDepartmentList: `${ctx}/api/user/department/list.do`,
  importExcel: `${ctx}/api/user/import_excel.do`,
  departmentOwnerList: `${ctx}/api/user/department/owner_list.do`,
  departmentCorpTree: `${ctx}/api/user/department/corp_tree.do`,
  userList: `${ctx}/api/user/list.do`,
  exportUser: `${ctx}/api/user/export_user.do`,
  getListRole: `${ctx}/api/system_auth/list_role.do`,
  addRole: `${ctx}/api/system_auth/add_role.do`,
  removeRole: `${ctx}/api/system_auth/remove_role.do`,
  updateRole: `${ctx}/api/system_auth/update_role.do`,
  getListAdmin: `${ctx}/api/system_auth/list_admin.do`,
  getRoleDetail: (roleId) => `${ctx}/api/system_auth/role_detail.do?roleId=${roleId}`,
  getPoolList: `${ctx}/api/pool/list.do`,
  getPoolAllotList: `${ctx}/api/pool/allot/list.do`,
  getPoolOrgList: `${ctx}/api/pool/org/list.do`,
  getPoolStaffList: `${ctx}/api/pool/staff_list.do`,
  setPoolAllot: `${ctx}/api/pool/allot.do`,
  getStaffPrivileges: `${ctx}/api/index/privileges.do`,
  logout: `${ctx}/index/logout.do`,
  staffRoleTypes: `${ctx}/api/system_auth/staff_role_types.do`,
  userCreate: `${ctx}/api/user/create.do`,
  avatarUpload: `${ctx}/api/user/avatar/upload.do`,
  userDetail: `${ctx}/api/user/detail.do`,
  userDelete: `${ctx}/api/user/delete.do`,
  departmentCreate: `${ctx}/api/user/department/create.do`,
  updateStatus: `${ctx}/api/user/updateStatus.do`,
  departmentUpdate: `${ctx}/api/user/department/update.do`,
  departmentDelete: `${ctx}/api/user/department/delete.do`,
  userUpdate: `${ctx}/api/user/update.do`,
  pushSetting: `${ctx}/api/news/edit_org`,
  getPushSetting: `${ctx}/api/news/list_notice_org`,
  newsList: `${ctx}/api/news/list.do`,
  mustSend: `${ctx}/api/news/mustsend.do`,
  notMustSend: `${ctx}/api/news/not_mustsend.do`,
  newsStatistics: `${ctx}/api/news/statistics.do`,
  newsDetail: `${ctx}/api/news/detail.do`,
  newsTagList: `${ctx}/api/news/tag/list.do`,
  newsTagCreate: `${ctx}/api/news/tag/create.do`,
  newsPeerCreate: `${ctx}/api/news/peer/create.do`,
  newsInformationList: `${ctx}/api/news/information/list.do`,
  newsInformationCreate: `${ctx}/api/news/information/create.do`,
  newsInformationDelete: `${ctx}/api/news/information/delete.do`,
  newsUpload: `${ctx}/api/news/upload.do`,
  newsCreate: `${ctx}/api/news/create.do`,
  contractTree: `${ctx}/api/user/department/contract/tree.do`,
  useStatistics: `${ctx}/api/user/use/statistics.do`,
  exportUseStatistics: `${ctx}/api/user/export_use_statistics.do`,
  useDetail: `${ctx}/api/user/use/detail.do`,
  exportUseDetail: `${ctx}/api/user/export_use_detail.do`,
  exportResult: `${ctx}/api/user/export_result.do`,
  getListMembers: `${ctx}/api/chat/list_members.do`,
  getListPartners: `${ctx}/api/chat/list_partners.do`,
  getListGroups: `${ctx}/api/chat/list_groups.do`,
  getListRecords: `${ctx}/api/chat/list_records.do`,
  getListQueryRecords: `${ctx}/api/chatlog/list_query_records.do`,
  chatlogDownload: `${ctx}/api/chatlog/download_file.do`,
  exportChatmsg: `${ctx}/api/chat/export_chatmsg.do`,
  sendRemindMsg: `${ctx}/api/chatlog/send_remind_msg.do`,
  setBusinessType: `${ctx}/api/user/update/business_type.do`,
  getProductTypeList: `${ctx}/api/product/type/list.do`,
  updateProductTypeSeq: `${ctx}/api/product/type/update_seq.do`,
  productFileUpload: `${ctx}/api/product/file/upload.do`,
  productCreate: `${ctx}/api/product/create.do`,
  productUpdate: `${ctx}/api/product/update.do`,
  getProductList: `${ctx}/api/product/list.do`,
  getProductDetail: `${ctx}/api/product/detail.do`,
  updateSeq: `${ctx}/api/product/update_seq.do`,
  productDelete: `${ctx}/api/product/delete.do`,
  getListNotifyUser: `${ctx}/api/chat/notifyUser/listNotifyUser.do`,
  changeNotifyUser: `${ctx}/api/chat/notifyUser/changeNotifyUser.do`,
  notifyUserSendMsg: `${ctx}/api/chat/notifyUser/sendMsg.do`,
  notifyUserStatus: `${ctx}/api/chat/notifyUser/status.do`,
  bannerUpload: `${ctx}/api/banner/upload.do`,
  choicestUpload: `${ctx}/api/choicest/upload`,
  bannerCreate: `${ctx}/api/banner/create.do`,
  bannerList: `${ctx}/api/banner/list.do`,
  bannerDelete: `${ctx}/api/banner/delete.do`,
  bannerUpdateSeq: `${ctx}/api/banner/update_seq.do`,
  bannerDetail: `${ctx}/api/banner/detail.do`,
  bannerUpdate: `${ctx}/api/banner/update.do`,
  newsListCategory: `${ctx}/api/news/list_category.do`,
  virtualDeptCreate: `${ctx}/api/virtual/dept/create`,
  virtualDeptList: `${ctx}/api/virtual/dept/list`,
  virtualDeptDelete: `${ctx}/api/virtual/dept/delete`,
  virtualDeptDetail: `${ctx}/api/virtual/dept/detail`,
  virtualDeptUpdate: `${ctx}/api/virtual/dept/update`,
  speechCreate: `${ctx}/api/product/speech/create.do`,
  speechDelete: `${ctx}/api/product/speech/delete.do`,
  speechUpdate: `${ctx}/api/product/speech/update.do`,
  speechUpdateSeq: `${ctx}/api/product/speech/update_seq.do`,
  speechUpload: `${ctx}/api/product/speech/upload.do`,
  speechList: `${ctx}/api/product/speech/list.do`,
  issueCreate: `${ctx}/api/product/issue/create.do`,
  issueDelete: `${ctx}/api/product/issue/delete.do`,
  issueUpdate: `${ctx}/api/product/issue/update.do`,
  issueUpdateSeq: `${ctx}/api/product/issue/update_seq.do`,
  issueUpload: `${ctx}/api/product/issue/upload.do`,
  issueList: `${ctx}/api/product/issue/list.do`,
  speechTemplate: `https://image0.tengmoney.com/templates/file/批量导入营销话术模板.xlsx`,
  issueTemplate: `https://image0.tengmoney.com/templates/file/批量导入问题描述模板.xlsx`,
  newsSendToCorp: `${ctx}/api/news/send_to_corp`,
  productLogList: `${ctx}/api/product/log/list.do`,
  msgListDept: `${ctx}/api/push/msg/list_dept.do`,
  msgUpdateDept: `${ctx}/api/push/msg/update_dept.do`,
  sentenceList: `${ctx}/api/sentence/list`,
  sentenceDetail: `${ctx}/api/sentence/detail`,
  sentenceLogList: `${ctx}/api/sentence/log/list`,
  sentenceAdd: `${ctx}/api/sentence/add`,
  sentenceEdit: `${ctx}/api/sentence/edit`,
  sentenceDel: `${ctx}/api/sentence/del`,
  uploadImg: `${ctx}/api/applet/file/upload.do`,
  sentenceImport: `${ctx}/api/sentence/import`,
  sentenceDownload: `https://image0.tengmoney.com/templates/file/导入模板.xls`,
  msgListLeader: `${ctx}/api/push/msg/list_leader.do`,
  msgSelectLeader: `${ctx}/api/push/msg/select_leader.do`,
  msgUpdateLeader: `${ctx}/api/push/msg/update_leader.do`,
  productOnOff: `${ctx}/api/product/on_off.do`,
  analyseList: `${ctx}/api/data/analyse/list.do`,
  analyseExportStatus: `${ctx}/api/data/analyse/export_status.do`,
  analyseExport: `${ctx}/api/data/analyse/export.do`,
  newsHotDelete: `${ctx}/api/news/delete.do`,
  fileList: `${ctx}/api/sidebar/list`,
  fileAdd: `${ctx}/api/sidebar/add`,
  fileInfo: `${ctx}/api/sidebar/get`,
  fileDel: `${ctx}/api/sidebar/del`,
  getIcons: `${ctx}/api/sidebar/icons`,
  sentenceSenceList: `${ctx}/api/sentence/sence/list`,
  sentenceSenceDel: `${ctx}/api/sentence/sence/del`,
  sentenceSenceAdd: `${ctx}/api/sentence/sence/add`,
  sentenceSenceEdit: `${ctx}/api/sentence/sence/edit`,
  sentenceSenceDetail: `${ctx}/api/sentence/sence/detail`,
  saveOrPush: `${ctx}/api/ppLink/message/saveOrPush.do`,
  messageQuery: `${ctx}/api/ppLink/message/query.do`,
  defaultMessageUpdate: `${ctx}/api/ppLink/message/defaultMessage/update.do`,
  defaultMessageDelete: `${ctx}/api/ppLink/message/defaultMessage/delete.do`,
  handMessagecCancel: `${ctx}/api/ppLink/message/handMessage/cancel.do`,
  pushRecordQuery: `${ctx}/api/ppLink/message/pushRecord/query.do`,
  queryDetail: `${ctx}/api/ppLink/message/defaultMessage/queryDetail.do`,
  newsEditTags: `${ctx}/api/news/edit_tags`,
  productPush: `${ctx}/api/product/push`,
  pushAnalysis: `${ctx}/api/ppLink/pushAnalysis.do`,
  assistantInfo: `${ctx}/api/ppLink/assistant_info.do`,
  qAssistant: `${ctx}/api/ppLink/qAssistant.do`,
  recordList: `${ctx}/api/data/analyse/record_list.do`,
  recordExport: `${ctx}/api/data/analyse/record_export.do`,
  pushRecordDelete: `${mockCtx}/api/ppLink/message/pushRecord/delete.do`,
  enterpriseListQuery: `${ctx}/api/ppLink/enterpriseList.do`,
  enterpriseAllTags: `${ctx}/api/ppLink/enterpriseAllTags.do`,
  enterpriseInfo: `${ctx}/api/ppLink/enterpriseInfo.do`,
  updateArticleSwitch: `${mockCtx}/api/switch/create`,
  editEnterpriseInfo: `${ctx}/api/ppLink/enterpriseModify.do`,
  batchEtpModify: `${ctx}/api/ppLink/batchEtpModify.do`,
  switchList: `${ctx}/api/switch/list`,
  switchCreate: `${ctx}/api/switch/create`,
  ppLinkUserList: `${ctx}/api/ppLink/userList.do`,
  updateUserTags: `${ctx}/api/ppLink/updateUserTags.do`,
  getBusinessList: `${ctx}/api/station/jump/list`,
  getOrgDetail: `${ctx}/api/station/jump/detail`,
  getColorInfo: `${ctx}/api/station/customize/bgcolor`,
  commitBusinessConfig: `${ctx}/api/station/jump/create`,
  BusinessConfigDelete: `${ctx}/api/station/jump/delete`,
  nowxnewsCreate: `${ctx}/api/news/nowxnews/create.do`,
  fileToHtml: `${ctx}/api/news/file_to_html/upload.do`,
  listStaffRoles: `${ctx}/api/system_auth/list_staff_roles.do`,
  setStaffRole: `${ctx}/api/system_auth/set_staff_role.do`,
  updateRolePermissions: `${ctx}/api/system_auth/update_role_permissions.do`,
  deleteRole: `${ctx}/api/system_auth/delete_role.do`,
  deptUser: `${ctx}/api/user/dept_user`,
  roleUserList: `${ctx}/api/system_auth/role_user_list`,
  roleUserUpload: `${ctx}/api/system_auth/role_user_upload`,
  deptStaffList: `${ctx}/api/user/department/dept_staff_list.do`,
  roleUserAdd: `${ctx}/api/system_auth/role_user_add`,
  roleUserDel: `${ctx}/api/system_auth/role_user_del`,
  listRolePermissions: `${ctx}/api/system_auth/list_role_permissions.do`,
  bannerConfig: `${ctx}/api/banner/getConfig`,
  getColorList: `${ctx}/api/station/customize/bgcolor`,
  updateColor: `${ctx}/api/station/customize/create_bgcolor`,
  getShareData: `${ctx}/api/station/customize/share`,
  bannerConfigReset: `${ctx}/api/banner/config`,
  parseHtml: (url) => `${ctx}/api/product/url/analysis.do?url=${url}`,
  updateShareConfig: `${ctx}/api/station/customize/create_share`,
  updateCommonSpeechIssue: `${ctx}/api/product/update_common_speech_issue.do`,
  createProduceCatagory: `${ctx}/api/product/type/save.do`,
  updateProduceCatagory: `${ctx}/api/product/type/edit.do`,
  deleteProduceCatagory: `${ctx}/api/product/type/delete.do`,
  shareGetConfig: `${ctx}/api/share/getConfig.do`,
  shareAddConfig: `${ctx}/api/share/addConfig.do`,
  sidebarNewsInfo: `${ctx}/api/sidebar_news_info/list.do`,
  newsTypes: `${ctx}/api/sidebar_news_info/news_types`,
  sidebarNewsCreate: `${ctx}/api/sidebar_news_info/create.do`,
  sidebarNewsDelete: `${ctx}/api/sidebar_news_info/delete.do`,
  sidebarNewsUpdate: `${ctx}/api/sidebar_news_info/update.do`,
  shareUpdateConfig: `${ctx}/api/share/updateConfig.do`,
  fileUpload: `${ctx}/api/applet/file/upload.do`,
  keydata: (deptid, date) => `${ctx}/api/databoard/keydata?deptid=${deptid}&date=${date}`,
  keydatatrend: (deptid, keydatatype, dateType) => `${ctx}/api/databoard/keydatatrend?deptid=${deptid}&keydatatype=${keydatatype}&dateType=${dateType}`,
  exportKeydata: (deptid, keydatatype, dateType) => `${ctx}/api/databoard/export_keydata?deptid=${deptid}&keydatatype=${keydatatype}&dateType=${dateType}`,
  listTypeIcon: `${ctx}/api/product/listTypeIcon.do`,
  databoardHotproduct: `${ctx}/api/databoard/hotproduct/list`,
  hotproductUp: `${ctx}/api/databoard/hotproduct/up`,
  saveStaffParam: `${ctx}/api/page/save.do`,
  findDetail: `${ctx}/api/page/find_detail.do`,
  hotproductExport: `${ctx}/api/databoard/hotproduct/export`,
  leaderboardTitle: `${ctx}/api/databoard/leaderboardTitle`,
  contentLeaderboard: `${ctx}/api/databoard/contentLeaderboard`,
  exportContentLeader: `${ctx}/api/databoard/exportContentLeader`,
  checkDeleteable: (id) => `${ctx}/api/product/is/delete.do?id=${id}`,
  qrodeList: `${ctx}/api/channel/qrode/list.do`,
  qrodeCreate: `${ctx}/api/channel/qrode/create.do`,
  getCardSettings: `${ctx}/card_settings/get`,
  saveCardSettings: `${ctx}/card_settings/save`,
  bannerPushCheck: `${ctx}/api/banner/push_check`,
  bannerPush: `${ctx}/api/banner/push`,
  qrodeUpdate: `${ctx}/api/channel/qrode/update.do`,
  tagCreate: `${ctx}/api/channel/qrode/tag/create.do`,
  tagList: `${ctx}/api/corpQywxCustomerTag/listTreeTags`,
  tagUpdate: `${ctx}//api/channel/qrode/tag/update.do`,
  getPosterList: `${ctx}/api/poster/list`,
  savePosterAdd: `${ctx}/api/poster/add`,
  savePosterEdit: `${ctx}/api/poster/edit`,
  deletePoster: `${ctx}/api/poster/del`,
  getPushProductList: `${ctx}/api/product/push/list.do`,
  cancelPushProduct: `${ctx}/api/product/cancel/push.do`,
  pushProductOrder: `${ctx}/api/product/push/order.do`,
  pushProductCheck: `${ctx}/api/product/push_check`,
  intendedClient: `${ctx}/api/data/intention_client/list`,
  exportIntendedClient: `${ctx}/api/data/intention_client/export_excel`,
  intendedExportStatus: (id) =>
    `${ctx}/api/data/intention_client/export_status?id=${id}`,
  appliationStatistics: `${ctx}/api/product/appliation/statistics`,
  statisticsExport: `${ctx}/api/product/appliation/statistics/export`,
  categoryList: `${ctx}/api/news/manage/category/all`,
  updateCategoryList: `${ctx}/api/news/manage/category/updateSeq`,
  tagsCreate: `${ctx}/api/news/manage/category/tags/create`,
  tagsUpdate: `${ctx}/api/news/manage/category/update`,
  deleteTags: `${ctx}/api/news/manage/category/delete`
}
